apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone_project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone_project
  template:
    metadata:
      labels:
        app: capstone_project
    spec:
      containers:
      - name: capstone_project
        image: abhiranjan88/capstone_project
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: capstone_project
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: capstone_project
